### ISSUE TITLE
[Lecture Topic Task] Create User Stories for the College Planning Feature

### ISSUE THREAD

**Issue by J3SSY-ANDU** [uprm-inso4101-2024-2025-s1/semester-project-regiupr#202]
Objective:
To define user stories that capture the functional requirements of the College Planning feature from the user's perspective, following Agile methodology.

Description:
Develop user stories to describe the key functionalities of the College Planning feature. The user stories should align with the needs of students managing their academic plans, focusing on actions like adding courses, tracking progress, and viewing semester details.

Requirements:

Write at least five user stories for the College Planning feature.
Use the standard Agile format:
As a [user role], I want to [action] so that [benefit].
Include acceptance criteria for each story to define when the feature is complete.
Ensure the stories cover a range of functionalities, such as:
Adding or removing courses.
Viewing and navigating between semesters.
Tracking GPA and credits.
Viewing overall progress toward degree completion.

Assignee:
@J3SSY-ANDU 

Time Constraints:
Should be completed by the end of Milestone 3.

Difficulty:
2

Priority:
3

**Comment by J3SSY-ANDU** [comment]
# User Stories for the College Planning Feature

Below are the user stories written in Agile format, with corresponding acceptance criteria:

---

## 1. Add Courses to a Semester Plan
**User Story:**
As a **student**, I want to **add courses to my semester plan** so that **I can organize my academic schedule effectively**.

**Acceptance Criteria:**
- The user can view a list of available courses filtered by eligibility and prerequisites.
- The user can drag and drop a course into a semester plan.
- An error message is displayed if the course conflicts with another or exceeds the allowed credit limit.

---

## 2. Remove Courses from a Semester Plan
**User Story:**
As a **student**, I want to **remove courses from my semester plan** so that **I can update my schedule if my plans change**.

**Acceptance Criteria:**
- The user can click on a course in the semester plan to remove it.
- A confirmation prompt is displayed before the course is removed.
- The removed course reappears in the list of available courses.

---

## 3. View Semester Details
**User Story:**
As a **student**, I want to **view the details of a selected semester** so that **I can see the courses I’ve planned and their schedules**.

**Acceptance Criteria:**
- The user can switch between semesters using a tabbed interface.
- Each semester displays a list or grid of courses along with their details (e.g., course code, title, credits, and schedule).
- Courses are color-coded based on their status (e.g., planned, completed, or in-progress).

---

## 4. Track GPA and Credits
**User Story:**
As a **student**, I want to **track my GPA and earned credits** so that **I can monitor my academic performance and progress toward graduation**.

**Acceptance Criteria:**
- The user can view their current GPA and total earned credits in the planner interface.
- GPA and credits automatically update as courses are added or removed.
- A tooltip or detailed breakdown is available for GPA calculation (e.g., grades, weighted credits).

---

## 5. View Overall Progress Toward Degree Completion
**User Story:**
As a **student**, I want to **view my progress toward degree completion** so that **I can understand how close I am to graduating**.

**Acceptance Criteria:**
- The user can view a progress bar or pie chart indicating the percentage of completed, in-progress, and pending requirements.
- A summary of completed core, major, and elective requirements is displayed.
- The user is alerted if they are missing any critical requirements.

**Comment by Yamil-Serrano** [comment]
# User Stories for the College Planning Feature  

Below are the user stories written in Agile format, with corresponding acceptance criteria:  

---

## 1. Log In to the Application  
**User Story:**  
As a student, I want to log in using my student number, email, and password so that I can securely access my academic profile.  

**Acceptance Criteria:**  
- The login screen displays input fields for email, student number, and password.  
- The system verifies credentials and redirects the user to the main menu upon successful login.  
- An error message appears for incorrect credentials or missing fields.  
- A language toggle button is available at the bottom right to switch between English and Spanish.  

---

## 2. View Profile Information  
**User Story:**  
As a student, I want to access my profile information so that I can view my personal and academic details.  

**Acceptance Criteria:**  
- A "Profile" button is visible in the main menu sidebar.  
- Clicking the button displays a profile page with the student’s name, ID, email, and academic progress (e.g., completed credits, GPA).  
- The language toggle button is available at the bottom right of the profile screen.  

---

## 3. Explore Available Courses  
**User Story:**  
As a student, I want to view available courses organized by department so that I can easily plan my semester.  

**Acceptance Criteria:**  
- A "Register for Courses" button in the main menu redirects to a course registration page.  
- Courses are displayed in a vertical sidebar organized by department (e.g., ESPA, INGL, INGE).  
- Courses are color-coded:  
  - **Green:** Eligible to enroll.  
  - **Yellow:** Requires co-requisites.  
  - **Orange:** Requires prerequisites.  
- Clicking a course displays its sections with details (days, times, professors).  

---

## 4. Create a Conflict-Free Schedule  
**User Story:**  
As a student, I want to build my schedule without overlapping courses so that I can avoid conflicts.  

**Acceptance Criteria:**  
- Selected courses are displayed on a weekly schedule (Monday to Friday) on the right side of the screen.  
- A warning message appears if two courses overlap in time.  
- The system allows the user to remove or modify conflicting courses/sections.  
- A confirmation message appears when the schedule is successfully created.  

---

## 5. Finalize Course Registration  
**User Story:**  
As a student, I want to finalize my course registration so that I can secure my spot in the selected classes.  

**Acceptance Criteria:**  
- A "Submit Registration" button is available at the bottom of the course registration page.  
- Clicking the button confirms the registration and saves the schedule.  
- A success message appears, summarizing the registered courses and sections.  
- Registered courses are marked as "In Progress" in the profile view.  

---

## 6. Navigate Between Semesters  
**User Story:**  
As a student, I want to switch between semesters so that I can plan my schedule for different academic terms.  

**Acceptance Criteria:**  
- A tab or dropdown menu is available to switch between semesters (e.g., Fall 2024, Spring 2025).  
- The selected semester dynamically updates the list of courses and the schedule view.  
- The system remembers the last selected semester during the session.  

---

## 7. View Overall Progress Toward Degree Completion  
**User Story:**  
As a student, I want to view my overall progress toward degree completion so that I can understand what requirements I still need to fulfill. 

---

## 8. Switch Application Language  
**User Story:**  
As a student, I want to toggle the application language between English and Spanish so that I can use it in my preferred language.  

**Acceptance Criteria:**  
- A language toggle button is visible on the login screen and profile screen.  
- The toggle changes the UI text between English and Spanish dynamically.  
- The system remembers the chosen language for future logins.  

---

**Comment by Jeanpaul-Ortiz** [comment]
# User Stories for the College Planning Feature

Below are the user stories written in Agile format, with corresponding acceptance criteria:

---

## 1. Validate Course Prerequisites Automatically

**User Story:**  
As a student, I want the system to validate prerequisites when adding a course so that I can ensure I meet the requirements without manually checking.

**Acceptance Criteria:**  
- The system checks prerequisites automatically when a course is selected.  
- If prerequisites are not met, a detailed error message is displayed explaining the missing requirements.  
- The user is guided to courses that fulfill the prerequisites if applicable.

---

## 2. Search for Courses by Keyword

**User Story:**  
As a student, I want to search for courses by keyword so that I can quickly find classes that match my interests or fulfill specific requirements.

**Acceptance Criteria:**  
- A search bar is available on the "Available Courses" screen.  
- The search allows for filtering by keyword and semester.  
- Clicking on a result shows detailed information about the course and sections.

---

## 3. Receive Warnings for Unmet Prerequisites  

**User Story:**  
As a student, I want to be warned if I select courses that have unmet prerequisites so that I can adjust my schedule accordingly.

**Acceptance Criteria:**  
- The system highlights courses that cannot be taken due to unmet prerequisite chains.  
- A tooltip explains the order of courses required to satisfy the dependency.  
- The system offers alternative paths to meet the prerequisite requirements, if available.

---

## 4. Course Recommendations Based on Semester

**User Story:**  
As a student, I want to receive course recommendations based on my current or planned semester so that I can explore options that align with my progress.

**Acceptance Criteria:**  
- The system provides a list of recommended courses when planning or viewing a semester.  
- Recommendations are based on the user’s major, GPA, and courses completed in prior semesters.  
- Filters are available to refine recommendations by semester or specific requirements.  
- Clicking on a recommendation displays course details and sections.

---

## 5. Save Planner States

**User Story:**  
As a student, I want to save my planner state so that I can revisit and use it for planning future semesters.

**Acceptance Criteria:**  
- An option to save the plan allows the user to save their current academic plan.  
- Saved plans are labeled by semester and are accessible from the planner menu.  
- The user can create multiple saved plans for different semesters or scenarios.

---

These user stories were collaboratively created by @Jeanpaul-Ortiz, @J3SSY-ANDU  and  @Nekyro . The contributions reflect a joint effort to align the stories with the requirements and goals of the College Planning feature.
